(ns oberon-clj.core
  (:require
   ;; [org.bytedeco.javacpp.LLVM :as llvm]
   [clojure.data]
   [instaparse.core :as instaparse])
  (:use [clojure.tools.macro :only (macrolet)]
        [gui.diff])
  (:gen-class))

(def oberon-parser
  (instaparse/parser (slurp "./resources/oberon-07.ebnf") :start :module :auto-whitespace :standard))

(def oberon-test-code
  "Code for testing Oberon parser. Source: http://groups.engin.umd.umich.edu/CIS/course.des/cis400/oberon/hworld.html "
  (macrolet [(compile-time-slurp [file] (slurp file))] ; local macro definition
            (slurp  "./resources/hello_world.mod")))

(def test-oberon-syntax
  "Tests oberon parser, causes Class exception in the case of failure as instaparse failure object cannot be casted into Clojure IFn(I think)"
  (instaparse/parse oberon-parser oberon-test-code))

(defn diff-syntax-tree []
  "Diffs syntax trees generated by instaparse due to ambiguity. Use for debugging only. See security warning in comment."
  ((fn [code] (let [a (first code)
                   b (second code)]
               (eval `(gui-diff ~a ~b)))) ;; Stupid macro magic because gui-diff quoted its arguments.
   ;; Note: Do not use for stuff where code injection is a concern. Use for debugging only.
   ;; See https://groups.google.com/forum/#!topic/clojure/EsBkz5uXZmU
   ;; and https://stackoverflow.com/questions/30766936/clojure-quoting-inside-let
   (take 2 (instaparse/parses oberon-parser oberon-test-code))))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!"))
